version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongodb_prueba
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - nest-network

  api:
    build: .
    container_name: nestjs_api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:

      - MONGO_URI=mongodb://mongo:27017/prueba-tecnica
    networks:
      - nest-network

volumes:
  mongo-data:


networks:
  nest-network:
